#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTP.QRCODE_HVN.NhanLaiNG
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="B7R2_FCC")]
	public partial class NHAN_HVN_NGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTMPPHIEUGIAOHANGDBCT(TMPPHIEUGIAOHANGDBCT instance);
    partial void UpdateTMPPHIEUGIAOHANGDBCT(TMPPHIEUGIAOHANGDBCT instance);
    partial void DeleteTMPPHIEUGIAOHANGDBCT(TMPPHIEUGIAOHANGDBCT instance);
    partial void InsertTMPPHIEUNHANDB(TMPPHIEUNHANDB instance);
    partial void UpdateTMPPHIEUNHANDB(TMPPHIEUNHANDB instance);
    partial void DeleteTMPPHIEUNHANDB(TMPPHIEUNHANDB instance);
    #endregion
		
		public NHAN_HVN_NGDataContext() : 
				base(global::PCTP.Properties.Settings.Default.B7R2_FCCConnectionString5, mappingSource)
		{
			OnCreated();
		}
		
		public NHAN_HVN_NGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NHAN_HVN_NGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NHAN_HVN_NGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NHAN_HVN_NGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TMPPHIEUGIAOHANGDBCT> TMPPHIEUGIAOHANGDBCTs
		{
			get
			{
				return this.GetTable<TMPPHIEUGIAOHANGDBCT>();
			}
		}
		
		public System.Data.Linq.Table<TMPPHIEUNHANDB> TMPPHIEUNHANDBs
		{
			get
			{
				return this.GetTable<TMPPHIEUNHANDB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMPPHIEUGIAOHANGDBCT")]
	public partial class TMPPHIEUGIAOHANGDBCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _IDP;
		
		private string _GGFCC;
		
		private System.Nullable<short> _STT;
		
		private string _CUA;
		
		private string _TRUYEN;
		
		private string _MAHANG;
		
		private string _TENHANG;
		
		private string _LOT;
		
		private string _DV;
		
		private System.Nullable<short> _SOLUONG;
		
		private System.Nullable<System.DateTime> _NGAYGIAO;
		
		private string _GIOGIAO;
		
		private string _STATUS;
		
		private string _TTPHIEU;
		
		private string _NHAMAY;
		
		private System.Nullable<int> _ADDNM;
		
		private System.Nullable<int> _HOP;
		
		private string _STATUSDOC;
		
		private System.Nullable<System.DateTime> _NGAYNHAN;
		
		private System.Nullable<bool> _TTNHAN;
		
		private string _Note;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDPChanging(System.Nullable<int> value);
    partial void OnIDPChanged();
    partial void OnGGFCCChanging(string value);
    partial void OnGGFCCChanged();
    partial void OnSTTChanging(System.Nullable<short> value);
    partial void OnSTTChanged();
    partial void OnCUAChanging(string value);
    partial void OnCUAChanged();
    partial void OnTRUYENChanging(string value);
    partial void OnTRUYENChanged();
    partial void OnMAHANGChanging(string value);
    partial void OnMAHANGChanged();
    partial void OnTENHANGChanging(string value);
    partial void OnTENHANGChanged();
    partial void OnLOTChanging(string value);
    partial void OnLOTChanged();
    partial void OnDVChanging(string value);
    partial void OnDVChanged();
    partial void OnSOLUONGChanging(System.Nullable<short> value);
    partial void OnSOLUONGChanged();
    partial void OnNGAYGIAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYGIAOChanged();
    partial void OnGIOGIAOChanging(string value);
    partial void OnGIOGIAOChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnTTPHIEUChanging(string value);
    partial void OnTTPHIEUChanged();
    partial void OnNHAMAYChanging(string value);
    partial void OnNHAMAYChanged();
    partial void OnADDNMChanging(System.Nullable<int> value);
    partial void OnADDNMChanged();
    partial void OnHOPChanging(System.Nullable<int> value);
    partial void OnHOPChanged();
    partial void OnSTATUSDOCChanging(string value);
    partial void OnSTATUSDOCChanged();
    partial void OnNGAYNHANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHANChanged();
    partial void OnTTNHANChanging(System.Nullable<bool> value);
    partial void OnTTNHANChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    #endregion
		
		public TMPPHIEUGIAOHANGDBCT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDP", DbType="Int")]
		public System.Nullable<int> IDP
		{
			get
			{
				return this._IDP;
			}
			set
			{
				if ((this._IDP != value))
				{
					this.OnIDPChanging(value);
					this.SendPropertyChanging();
					this._IDP = value;
					this.SendPropertyChanged("IDP");
					this.OnIDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GGFCC", DbType="NVarChar(50)")]
		public string GGFCC
		{
			get
			{
				return this._GGFCC;
			}
			set
			{
				if ((this._GGFCC != value))
				{
					this.OnGGFCCChanging(value);
					this.SendPropertyChanging();
					this._GGFCC = value;
					this.SendPropertyChanged("GGFCC");
					this.OnGGFCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="SmallInt")]
		public System.Nullable<short> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUA", DbType="NVarChar(50)")]
		public string CUA
		{
			get
			{
				return this._CUA;
			}
			set
			{
				if ((this._CUA != value))
				{
					this.OnCUAChanging(value);
					this.SendPropertyChanging();
					this._CUA = value;
					this.SendPropertyChanged("CUA");
					this.OnCUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRUYEN", DbType="NVarChar(50)")]
		public string TRUYEN
		{
			get
			{
				return this._TRUYEN;
			}
			set
			{
				if ((this._TRUYEN != value))
				{
					this.OnTRUYENChanging(value);
					this.SendPropertyChanging();
					this._TRUYEN = value;
					this.SendPropertyChanged("TRUYEN");
					this.OnTRUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHANG", DbType="NVarChar(50)")]
		public string MAHANG
		{
			get
			{
				return this._MAHANG;
			}
			set
			{
				if ((this._MAHANG != value))
				{
					this.OnMAHANGChanging(value);
					this.SendPropertyChanging();
					this._MAHANG = value;
					this.SendPropertyChanged("MAHANG");
					this.OnMAHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHANG", DbType="NVarChar(50)")]
		public string TENHANG
		{
			get
			{
				return this._TENHANG;
			}
			set
			{
				if ((this._TENHANG != value))
				{
					this.OnTENHANGChanging(value);
					this.SendPropertyChanging();
					this._TENHANG = value;
					this.SendPropertyChanged("TENHANG");
					this.OnTENHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOT", DbType="NVarChar(200)")]
		public string LOT
		{
			get
			{
				return this._LOT;
			}
			set
			{
				if ((this._LOT != value))
				{
					this.OnLOTChanging(value);
					this.SendPropertyChanging();
					this._LOT = value;
					this.SendPropertyChanged("LOT");
					this.OnLOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV", DbType="NVarChar(50)")]
		public string DV
		{
			get
			{
				return this._DV;
			}
			set
			{
				if ((this._DV != value))
				{
					this.OnDVChanging(value);
					this.SendPropertyChanging();
					this._DV = value;
					this.SendPropertyChanged("DV");
					this.OnDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="SmallInt")]
		public System.Nullable<short> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYGIAO", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYGIAO
		{
			get
			{
				return this._NGAYGIAO;
			}
			set
			{
				if ((this._NGAYGIAO != value))
				{
					this.OnNGAYGIAOChanging(value);
					this.SendPropertyChanging();
					this._NGAYGIAO = value;
					this.SendPropertyChanged("NGAYGIAO");
					this.OnNGAYGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOGIAO", DbType="NVarChar(50)")]
		public string GIOGIAO
		{
			get
			{
				return this._GIOGIAO;
			}
			set
			{
				if ((this._GIOGIAO != value))
				{
					this.OnGIOGIAOChanging(value);
					this.SendPropertyChanging();
					this._GIOGIAO = value;
					this.SendPropertyChanged("GIOGIAO");
					this.OnGIOGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(50)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTPHIEU", DbType="NVarChar(50)")]
		public string TTPHIEU
		{
			get
			{
				return this._TTPHIEU;
			}
			set
			{
				if ((this._TTPHIEU != value))
				{
					this.OnTTPHIEUChanging(value);
					this.SendPropertyChanging();
					this._TTPHIEU = value;
					this.SendPropertyChanged("TTPHIEU");
					this.OnTTPHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHAMAY", DbType="VarChar(50)")]
		public string NHAMAY
		{
			get
			{
				return this._NHAMAY;
			}
			set
			{
				if ((this._NHAMAY != value))
				{
					this.OnNHAMAYChanging(value);
					this.SendPropertyChanging();
					this._NHAMAY = value;
					this.SendPropertyChanged("NHAMAY");
					this.OnNHAMAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDNM", DbType="Int")]
		public System.Nullable<int> ADDNM
		{
			get
			{
				return this._ADDNM;
			}
			set
			{
				if ((this._ADDNM != value))
				{
					this.OnADDNMChanging(value);
					this.SendPropertyChanging();
					this._ADDNM = value;
					this.SendPropertyChanged("ADDNM");
					this.OnADDNMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOP", DbType="Int")]
		public System.Nullable<int> HOP
		{
			get
			{
				return this._HOP;
			}
			set
			{
				if ((this._HOP != value))
				{
					this.OnHOPChanging(value);
					this.SendPropertyChanging();
					this._HOP = value;
					this.SendPropertyChanged("HOP");
					this.OnHOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSDOC", DbType="NVarChar(50)")]
		public string STATUSDOC
		{
			get
			{
				return this._STATUSDOC;
			}
			set
			{
				if ((this._STATUSDOC != value))
				{
					this.OnSTATUSDOCChanging(value);
					this.SendPropertyChanging();
					this._STATUSDOC = value;
					this.SendPropertyChanged("STATUSDOC");
					this.OnSTATUSDOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAN", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYNHAN
		{
			get
			{
				return this._NGAYNHAN;
			}
			set
			{
				if ((this._NGAYNHAN != value))
				{
					this.OnNGAYNHANChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAN = value;
					this.SendPropertyChanged("NGAYNHAN");
					this.OnNGAYNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTNHAN", DbType="Bit")]
		public System.Nullable<bool> TTNHAN
		{
			get
			{
				return this._TTNHAN;
			}
			set
			{
				if ((this._TTNHAN != value))
				{
					this.OnTTNHANChanging(value);
					this.SendPropertyChanging();
					this._TTNHAN = value;
					this.SendPropertyChanged("TTNHAN");
					this.OnTTNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(250)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TMPPHIEUNHANDB")]
	public partial class TMPPHIEUNHANDB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDP;
		
		private string _NAME;
		
		private System.Nullable<bool> _TRANGTHAINHAN;
		
		private string _NOTE;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private int _NHAMAY;
		
		private string _NHAMAYNAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPChanging(int value);
    partial void OnIDPChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnTRANGTHAINHANChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAINHANChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnNHAMAYChanging(int value);
    partial void OnNHAMAYChanged();
    partial void OnNHAMAYNAMEChanging(string value);
    partial void OnNHAMAYNAMEChanged();
    #endregion
		
		public TMPPHIEUNHANDB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDP
		{
			get
			{
				return this._IDP;
			}
			set
			{
				if ((this._IDP != value))
				{
					this.OnIDPChanging(value);
					this.SendPropertyChanging();
					this._IDP = value;
					this.SendPropertyChanged("IDP");
					this.OnIDPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(250)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAINHAN", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAINHAN
		{
			get
			{
				return this._TRANGTHAINHAN;
			}
			set
			{
				if ((this._TRANGTHAINHAN != value))
				{
					this.OnTRANGTHAINHANChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAINHAN = value;
					this.SendPropertyChanged("TRANGTHAINHAN");
					this.OnTRANGTHAINHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(250)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHAMAY", DbType="Int NOT NULL")]
		public int NHAMAY
		{
			get
			{
				return this._NHAMAY;
			}
			set
			{
				if ((this._NHAMAY != value))
				{
					this.OnNHAMAYChanging(value);
					this.SendPropertyChanging();
					this._NHAMAY = value;
					this.SendPropertyChanged("NHAMAY");
					this.OnNHAMAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHAMAYNAME", DbType="NVarChar(50)")]
		public string NHAMAYNAME
		{
			get
			{
				return this._NHAMAYNAME;
			}
			set
			{
				if ((this._NHAMAYNAME != value))
				{
					this.OnNHAMAYNAMEChanging(value);
					this.SendPropertyChanging();
					this._NHAMAYNAME = value;
					this.SendPropertyChanged("NHAMAYNAME");
					this.OnNHAMAYNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
