using DevExpress.XtraEditors;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using PCTP.Modules.BaoCao.Application.Contracts;
using PCTP.Modules.BaoCao.Application.Contracts.Queries;
using PCTP.Modules.BaoCao.Infrastructure.Queries;
using System;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace PCTP.Modules.BaoCao.UI
{
    /// <summary>
    /// Stock history/current-stock reporting UI.
    /// The form contains presentation only; all SQL access is behind query ports.
    ///
    /// This form is intentionally code-built rather than generated by the
    /// WinForms designer. Keep the DesignerCategory attribute so Visual Studio
    /// does not try to parse the hand-written InitializeComponent method.
    /// </summary>
    [DesignerCategory("Code")]
    public sealed class FormBaoCaoStockHistory : XtraForm
    {
        private readonly IStockHistoryQuery _historyQuery;
        private readonly ICurrentStockQuery _currentStockQuery;
        private readonly CancellationTokenSource _lifetime = new CancellationTokenSource();

        private DateEdit _dateFrom;
        private DateEdit _dateTo;
        private LookUpEdit _lookupItemCode;
        private SimpleButton _btnSearch;
        private SimpleButton _btnCurrentStock;
        private SimpleButton _btnExport;
        private SimpleButton _btnPrint;
        private GridControl _grid;
        private GridView _view;
        private bool _showingCurrentStock;

        public FormBaoCaoStockHistory()
            : this(new StockHistoryQueryService(), new CurrentStockQueryService())
        {
        }

        public FormBaoCaoStockHistory(
            IStockHistoryQuery historyQuery,
            ICurrentStockQuery currentStockQuery)
        {
            if (historyQuery == null) throw new ArgumentNullException("historyQuery");
            if (currentStockQuery == null) throw new ArgumentNullException("currentStockQuery");

            _historyQuery = historyQuery;
            _currentStockQuery = currentStockQuery;

            InitializeComponent();
            Shown += async (s, e) => await LoadItemCodesAsync();
            FormClosed += (s, e) => _lifetime.Cancel();
        }

        private void InitializeComponent()
        {
            Text = "Báo cáo - Lịch sử kho";
            ClientSize = new System.Drawing.Size(1184, 672);
            StartPosition = FormStartPosition.CenterScreen;

            var top = new PanelControl { Dock = DockStyle.Top, Height = 72 };
            var historyGroup = new GroupControl { Text = "Tra cứu lịch sử nhập xuất", Dock = DockStyle.Fill };
            var currentGroup = new GroupControl { Text = "Kho hiện tại", Dock = DockStyle.Left, Width = 190 };
            var actionPanel = new PanelControl { Dock = DockStyle.Right, Width = 205 };

            _dateFrom = new DateEdit { Left = 12, Top = 32, Width = 145 };
            _dateFrom.Properties.NullText = "Từ ngày";
            _dateTo = new DateEdit { Left = 164, Top = 32, Width = 145 };
            _dateTo.Properties.NullText = "Đến ngày";
            _lookupItemCode = new LookUpEdit { Left = 316, Top = 32, Width = 205 };
            _lookupItemCode.Properties.NullText = "Mã hàng";
            _lookupItemCode.Properties.DisplayMember = "ItemCode";
            _lookupItemCode.Properties.ValueMember = "ItemCode";
            _btnSearch = new SimpleButton { Left = 526, Top = 29, Width = 90, Text = "Tìm kiếm" };
            _btnSearch.Click += async (s, e) => await SearchAsync();

            _btnCurrentStock = new SimpleButton { Left = 10, Top = 29, Width = 165, Text = "Thống kê kho hiện tại" };
            _btnCurrentStock.Click += async (s, e) => await LoadCurrentStockAsync();

            _btnExport = new SimpleButton { Left = 8, Top = 22, Width = 90, Text = "Xuất Excel" };
            _btnExport.Click += ExportClick;
            _btnPrint = new SimpleButton { Left = 105, Top = 22, Width = 90, Text = "In báo cáo" };
            _btnPrint.Click += PrintClick;

            historyGroup.Controls.AddRange(new Control[] { _dateFrom, _dateTo, _lookupItemCode, _btnSearch });
            currentGroup.Controls.Add(_btnCurrentStock);
            actionPanel.Controls.AddRange(new Control[] { _btnExport, _btnPrint });
            top.Controls.Add(historyGroup);
            top.Controls.Add(currentGroup);
            top.Controls.Add(actionPanel);

            _grid = new GridControl { Dock = DockStyle.Fill };
            _view = new GridView(_grid);
            _grid.MainView = _view;
            _grid.ViewCollection.Add(_view);

            Controls.Add(_grid);
            Controls.Add(top);
        }

        private async Task LoadItemCodesAsync()
        {
            try
            {
                var codes = await _historyQuery.GetItemCodesAsync(_lifetime.Token);
                _lookupItemCode.Properties.DataSource = codes;
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                XtraMessageBox.Show(this, ex.Message, "Không thể tải mã hàng", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private async Task SearchAsync()
        {
            try
            {
                _showingCurrentStock = false;
                var criteria = new HistorySearchCriteria
                {
                    From = ToDate(_dateFrom.EditValue),
                    To = ToDate(_dateTo.EditValue),
                    PartNo = _lookupItemCode.EditValue == null ? null : _lookupItemCode.EditValue.ToString()
                };

                var rows = await _historyQuery.SearchAsync(criteria, _lifetime.Token);
                _grid.DataSource = rows;
                _view.BestFitColumns();
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                XtraMessageBox.Show(this, ex.Message, "Không thể tra cứu lịch sử kho", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private async Task LoadCurrentStockAsync()
        {
            try
            {
                _showingCurrentStock = true;
                var rows = await _currentStockQuery.GetAsync(_lifetime.Token);
                _grid.DataSource = rows;
                _view.BestFitColumns();
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                XtraMessageBox.Show(this, ex.Message, "Không thể tải tồn kho hiện tại", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void ExportClick(object sender, EventArgs e)
        {
            if (_grid.DataSource == null) return;

            using (var dialog = new SaveFileDialog())
            {
                dialog.Filter = "Excel File (*.xlsx)|*.xlsx";
                dialog.FileName = (_showingCurrentStock ? "KhoHienTai_" : "LichSuNhapXuat_")
                    + DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".xlsx";

                if (dialog.ShowDialog(this) != DialogResult.OK) return;
                _view.ExportToXlsx(dialog.FileName);
                XtraMessageBox.Show(this, "Xuất Excel thành công!", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void PrintClick(object sender, EventArgs e)
        {
            if (_grid.DataSource == null) return;
            _view.OptionsPrint.AutoWidth = false;
            _view.OptionsPrint.PrintHeader = true;
            _view.OptionsPrint.PrintFooter = true;
            _grid.ShowPrintPreview();
        }

        private static DateTime? ToDate(object value)
        {
            if (value == null || value == DBNull.Value) return null;
            return Convert.ToDateTime(value);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _lifetime.Dispose();
            base.Dispose(disposing);
        }
    }
}
