//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCTP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.200.14\\BRAVO,1433;Initial Catalog=B7R2_FCC;Persist Security I" +
            "nfo=True;User ID=sa;Password=fccbrv")]
        public string B7R2_FCCConnectionString {
            get {
                return ((string)(this["B7R2_FCCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.200.14\\BRAVO;Initial Catalog=B7R2_FCC;Persist Security Info=T" +
            "rue;User ID=sa;Password=fccbrv")]
        public string B7R2_FCCConnectionString1 {
            get {
                return ((string)(this["B7R2_FCCConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.200.57;Initial Catalog=B7R2_FCC;User ID=sa;Password=fccbrv")]
        public string B7R2_57 {
            get {
                return ((string)(this["B7R2_57"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.200.57;Initial Catalog=B7R2_FCC;Persist Security Info=True;Us" +
            "er ID=sa;Password=fccbrv")]
        public string B7R2_FCCConnectionString2 {
            get {
                return ((string)(this["B7R2_FCCConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.200.14\\BRAVO;Initial Catalog=B7R2_FCC;Persist Security Info=T" +
            "rue;User ID=sa;Password=fccbrv")]
        public string B7R2_FCCConnectionString3 {
            get {
                return ((string)(this["B7R2_FCCConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.200.14\\BRAVO;Initial Catalog=B7R2_FCC;User ID=sa;Password=fcc" +
            "brv")]
        public string B7R2_FCCConnectionString4 {
            get {
                return ((string)(this["B7R2_FCCConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.200.14\\BRAVO;Initial Catalog=B7R2_FCC;User ID=sa;Password=fcc" +
            "brv;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string B7R2_FCCConnectionString5 {
            get {
                return ((string)(this["B7R2_FCCConnectionString5"]));
            }
        }
    }
}
